In [5]:
def sum(a,b):
  sum = a+b
  print(sum)
  
sum(2,4)


6


In [16]:
def big(a,b,c):
  if (a>b) and (a>c):
    print(a,"is big")
  elif (b>a) and (b>c):
    print(b, "is big")
  else:
    print(c, "is big")

big(9,7,2)      

9 is big


In [62]:
lis=[1,2,3]
max=0
for i in lis:
  if i > max:
    max = i
print(max)

3


In [0]:
a=[2,3,44,5]
b=[]
for i in range(len(a)-1,-1,-1):
  b.append(a[i])
print(b)

In [47]:
  a=0
  b=1
  n=7
  for i in range(1,n):
    c=a+b
    a=b
    b=c
    print(c)


1
2
3
5
8
13


In [49]:
def fibonacci(n):
  a=0
  b=1
  n=7
  for i in range(1,n):
    c=a+b
    a=b
    b=c
    print(c)

fibonacci(5)

1
2
3
5
8
13


In [61]:
import numpy as np
vector = np.array([1, 2, 3])
print(vector)
vector[:3]

[1 2 3]


array([1, 2, 3])

In [0]:
vector = np.array([[1,2,3],[4,5,6]])
print(vector)

vector_1 = np.array([1,2,3])
print(vector_1)

In [63]:
a=np.random.randn(3,3)
print(a)
b=np.random.randn(1,6,(3,3))
print(b)

[[-0.25425833 -0.26069793 -0.26924265]
 [ 0.80509865  0.75050866 -1.99708534]
 [ 0.12631105  1.03988986 -0.19797544]]
[[-1.87108991 -0.78148961  0.67352361]
 [-0.33726705  0.35617124 -0.20278025]
 [ 0.08588514 -1.22771475  1.7830428 ]]


In [64]:
cross_product = np.cross(a,b)
print(cross_product)

[[-0.38599655  0.6750262  -0.28908902]
 [ 0.55911603  0.83680918  0.53987483]
 [ 1.61111076 -0.24222116 -0.24438503]]


In [65]:
dot_product = np.dot(a,b)
print(dot_product)

[[ 0.54054108  0.43640032 -0.59845578]
 [-1.93105376  2.08998451 -3.17082403]
 [-0.60406306  0.51472546 -0.47879433]]


In [66]:
addition = np.add(a,b)
print(addition)

[[-2.12534824 -1.04218754  0.40428095]
 [ 0.46783161  1.1066799  -2.19986559]
 [ 0.21219619 -0.18782489  1.58506736]]
